# Generated by Django 5.1.6 on 2025-06-02 05:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventario", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productos",
            name="categoria",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="productos",
                to="inventario.categorias",
            ),
        ),
        migrations.AlterField(
            model_name="productos",
            name="marca",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="inventario.marcas",
            ),
        ),
        migrations.AlterField(
            model_name="productos",
            name="precio",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="productos",
            name="stock",
            field=models.PositiveIntegerField(),
        ),
    ]
